### ISSUE TITLE
Manifest Formatting

### ISSUE THREAD

**Issue by gmarnin** [edingc/munki-enroll#1]
First off, nice script. It does mostly everything I need to switch my manifest workflow from a few generic manifests to 1 manifest per Mac. 

When I run the script, I noticed the formatting of the xml manifest is off. The enroll.php script creates a manifest that looks like: 
`<
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict><key>catalogs</key><array><string>production</string></array><key>included_manifests</key><array><string>standard_apps</string></array></dict></plist>
`>

Instead of the stand xml file structure:
`<
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>catalogs</key>
    <array>
        <string>testing</string>
    </array>
    <key>managed_installs</key>
    <array>
    </array>
    <key>managed_uninstalls</key>
    <array>
    </array>
    <key>managed_updates</key>
        <array>
    </array>
    <key>optional_installs</key>
    <array>
    </array>
</dict>
</plist>
`>

Are you seeing this too? The formatting I'm seeing from enroll.php makes the manifest hard to edit compared to the standard xml manifest format.  Any ideas on how to correct?

**Comment by edingc** [comment]
As an update, I changed the default behavior in a later commit. bbe533f049588cbed403f0b93eb063f9805fd88d
