### ISSUE TITLE
munki-enroll creates clients/ folder but not manifest. 

### ISSUE THREAD

**Issue by wiegz** [edingc/munki-enroll#15]
I am trying to get munki-enroll working in my environment and I look forward to finally getting it down.  The script seems to be running fine.  I get the message "Computer manifest does not exist. Will create."  like I should when I run the script.  It creates the clients/ folder but no manifest is created.  I could keep running the script and it never creates a manifest for the computer.  I have checked to make sure the my web server has write access to the folders and everything.  I don't understand how it can make the folder but not the manifest.  Any input would be appreciated.  

Thanks for the tool!

ps: my munki_repo is on an Ubuntu server.  Also note that when the manifest already exists it states the correct message that it exists.

**Comment by edingc** [comment]
Can you please try this now that I've merged #14?

**Comment by wiegz** [comment]
Just tried again with the updates and the same thing is happening.  It will create the folder but no manifest.  
I make sure to have the machine I am testing on set to a default manifest that I created before running.   I have been messing around with the www-data write permissions on the folders and it is not helping.  If it is allowed to make the clients folder it should also be able to create the manifest I would think.  

I am not sure if this is much of a help but I am using Ubuntu 16.04.  PHP 7.0.8.

**Comment by justbazzar** [comment]
I'm experiencing the same issue using the latest version of munki-enroll. The clients folder is being created but no manifests ae being created. My Munki server is running on Centos 7

**Comment by justbazzar** [comment]
Did you get around the issue wiegz?

**Comment by edingc** [comment]
@justbazzar I am sorry this issue has been looked at closer. I don't have easy access to a test setup anymore now that I don't do any Mac administration. That being said, I spun up a CentOS 7 Linode, using Apache and PHP 5.4.16 this morning and was able to recreate your issue. I'm looking into it.

**Comment by wiegz** [comment]
I never got around the issue and because of time.  I am currently just using a basic munki setup.  When things settle down at work I was going to get back into the server and try and start from scratch.

**Comment by edingc** [comment]
@wiegz and @justbazzar 

Commit b7c15769df3eec27eb7804af3236159f0b0a1104 should resolve the problem. I've added some relevant debugging to the enroll.php script to help us out.

For CentOS 7, setup the environment (this assumes a standard Apache/PHP install with the munki_repo at `/var/www/html/munki_repo`:

`yum install httpd php php-xml`

Put munki-enroll at `/var/www/html/munki_repo/munki-enroll` and make sure Apache has correct access to the Munki repository:

`chmod -R a+rX,g+w /var/www/html/munki_repo`
`chown -R apache:apache /var/www/html/munki_repo`

On the local Mac, run the enroll script from the terminal:

`sudo ./munki_enroll.sh`

You should get output similar to the following:

    Computer hostname is: M762095
    Current ClientIdentifier is: base
    Target manifest location: /var/www/html/munki_repo/manifests/clients/M762095
    Computer manifest for M762095 does not exist. Will create.
    Clients folder /var/www/html/munki_repo/manifests/clients/ does not exist. Will create.
    Writing new plist to /var/www/html/munki_repo/manifests/clients/M762095

The manifest should be created correctly.

Ubuntu should be similar with `sudo apt-get install apache2 php php-xml`, but the paths may be slightly different.

**Comment by edingc** [comment]
@wiegz 

I spun up a 16.04 LTS box with PHP 7. This should get you what you need with the latest commit:

    apt-get install apache2 libapache2-mod-php php php-xml
    chmod -R a+rX,g+w /var/www/html/munki_repo
    chown -R www-data:www-data /var/www/html/munki_repo

**Comment by edingc** [comment]
@wiegz 

There is now a wiki page for setting up Munki/munki-enroll on Ubuntu 16.04 LTS: https://github.com/edingc/munki-enroll/wiki/Ubuntu-16.04-LTS-Setup

**Comment by justbazzar** [comment]
Hi, sorry for the delay in reporting back. I have finished setting up the munki server and can happily report that munki-enroll is now working perfectly after your latest changes Cody. Thank you so much for fixing this issue, your script is a big time saver and organisational tool in my Mac environment.

**Comment by edingc** [comment]
@justbazzar 

Great to hear. Thanks for the update. I am going to close this issue at this point.

**Comment by greaterfool** [comment]
This issue seems to be happening still.

**Comment by edingc** [comment]
> This issue seems to be happening still.

@greaterfool 

Can you please provide what operating system you are running the Munki repository on? What PHP version? What's the output from running the enroll script manually on a machine?
