### ISSUE TITLE
Computer manifest does not exist. Will create.

### ISSUE THREAD

**Issue by morgrowe** [edingc/munki-enroll#3]
First of all, thanks for writing this tool. I can't wait to get it up and running.

I've installed munki-enroll into my munki_repo just like your instructions state. I've then configured and copied the munki_enroll.sh script to one of my client machines that has munki installed and configured on it. All good so far.

However, when I execute the script (sudo ./munki_enroll.sh) I get this message:

Computer manifest does not exist. Will create.

If I look inside the /Library/Preferences/ManagedInstalls file on the client machine, I can see it has updated the ClientIdentifier key as expected. However, if I look on my munki server in the manifests directory, nothing has been created. Reading through the php file, it looks like it's supposed to create a folder within the manifests directory, but it doesn't get that far.

I'm running this on 10.10.2. The munki server is served using OS X Server application (version 4.0.3)

Any idea what's causing this problem? Maybe I haven't configured something properly or the tool is no longer compatible with OS X 10.10?

Kind regards,
Morgan

**Comment by edingc** [comment]
Hi Morgan:

Does the web server have write access to your Munki repository?

Thanks!

Cody

**Comment by morgrowe** [comment]
Hi Cody,

Ahhh, silly me. As soon as gave the web server write access all was well. Thanks for your help!

Morgan

**Comment by letrast** [comment]
I'm using OS X 10.11.5 with Server 5.1.5 as my munki repo.  Everything works fine except I can't get the machine manifests to auto create.  I saw this thread and blew permissions wide open to see if I could get it to work and it did.  Now I'm having trouble scaling it back.

Could someone tell me exactly what permissions need to be set for what folders in the repo for this to work?  Thanks!

**Comment by edingc** [comment]
@letrast -

I'm not sure what permissions you have changed, but the web server will need write access to the manifests folder inside your Munki repository at the very least.

**Comment by letrast** [comment]
@edingc 

Thanks.  I did a little more experimenting and figured out the issue, but your reply (and a good night's sleep) helped to unscramble my brain.
