### ISSUE TITLE
Manifest path

### ISSUE THREAD

**Issue by josephbeck17** [edingc/munki-enroll#5]
In my environment the manifests are being created at ../manifests/clients/client_name. If I look at ManagedInstalls.plist it lists the client identifier as /parent_manifest/clients/client_name. It seems that the $identifier_path variable used in the mkdir command on line 32 of enroll.php isn't being populated.

**Comment by edingc** [comment]
Joseph:

What's the output of the following script when run from a problematic computer?

    #!/bin/sh 
 
    IDENTIFIER=$( defaults read /Library/Preferences/ManagedInstalls ClientIdentifier ); 
    HOSTNAME=$( scutil --get ComputerName );
    IDENTIFIER_PATH=$( echo "$IDENTIFIER" | sed 's/\/[^/]*$//' ); 

    echo $IDENTIFIER;
    echo $HOSTNAME;
    echo $IDENTIFIED_PATH

    exit 0

**Comment by edingc** [comment]
Whoops, disregard the above comment. I misread your issue.

**Comment by josephbeck17** [comment]
admin/clients/Joseph-MBP
Joseph-MBP
(this line was blank)

**Comment by edingc** [comment]
What happens if you manually POST to the enroll script with variables through a web browser? Perhaps try editing the enroll.php script to echo the $identifier_path variable out to the screen to confirm your suspicion?

I apologize. I haven't worked on this project in a long time and no longer have a Mac to test with. I can setup a test, but it will take a little bit for me to properly try to reproduce your issue.

**Comment by josephbeck17** [comment]
I can just edit munki_enroll.sh to leave off the parent manifest in the client identifier or something. I'll test it a few different ways. Just wanted to make sure I wasn't missing anything trivial.

**Comment by mrmstevenson** [comment]
Had the exact same issue and apache2 logs confirmed the name client searching for the path that did not exists which resulted in managedsoftwareupdate failing. 

Considering uninstalling Munki Enrol as everytime we try fixing the /Library/Preferences/ManagedInstalls.plist gets overwritten now non of the enrolled clients work :-(

**Comment by edingc** [comment]
Joseph and Matt:

I just pushed a changed to munki_enroll.sh that should correct the issue you both reported. There was a bug in the shell script that failed to properly create the proper folder structure when the original manifest was located in the root of the manifests folder.

Can you please test this new script at your convenience?

Thanks.

**Comment by edingc** [comment]
Bug has been fixed based on my testing. Closing issue.
