### ISSUE TITLE
how to execute the munki_enroll.sh script

### ISSUE THREAD

**Issue by avasquez3593** [edingc/munki-enroll#6]
Can someone please tell me how i can execute the munki enroll script through terminal or Deploy Studio.

**Comment by edingc** [comment]
**Client Configuration**

Edit the included munki_enroll.sh script to include the full URL path to the enroll.php file on your Munki repository.

`SUBMITURL="https://munki/munki-enroll/enroll.php"`

The included munki_enroll.sh script can be executed in any number of ways (Terminal, ARD, DeployStudio workflow, LaunchAgent, etc.). Once the script is executed, the Client Identifier is switched to a unique identifier based on the system's hostname.

-----------------

Try **./munki_enroll.sh** from the Terminal or add a script step in your DeployStudio workflow. The latter is how it was deployed at my employer. You may need to `chmod +x` if you downloaded the script from the web.
